apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sdia-lw
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: deployer
  name: deployer
spec:
  selector:
    matchLabels:
      io.kompose.service: deployer
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: deployer
    spec:
      containers:
      - env:
        - name: AWX_USERNAME
          value: N2M0YjM4MzhmOWU0MDU4MzkxZTRkNGE3
        - name: AWX_BASE_PATH
          value: https://fry.lab.uvalight.net:8052
        - name: AWX_ADMIN_PASSWORD
          value: NDViYjdmNjBmMTE5NWI4MGQyNTZmMDhh
        - name: RABBITMQ_HOST
          value: rabbit
        - name: SEMAPHORE_BASE_PATH
          value: http://semaphore:3000/api
        - name: SURE_TOSCA_BASE_PATH
          value: http://sure-tosca:8081/tosca-sure/1.0.0
        - name: CREDENTIAL_SECRET
          value: MGY0MGQ1MDFkYzg5ZGIxYjY4MjQ4MzQz
        image: qcdis/sdia-deployer:1.0.4
        name: deployer
        resources: {}
      restartPolicy: Always
status: {}



