apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: conf
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: deployer
  name: deployer
spec:
  selector:
    matchLabels:
      io.kompose.service: deployer
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: deployer
    spec:
      containers:
      - env:
        - name: AWX_USERNAME
          value: N2M0YjM4MzhmOWU0MDU4MzkxZTRkNGE3
        - name: AWX_BASE_PATH
          value: https://bender.lab.uvalight.net:8052/api/v2
        - name: AWX_PASSWORD
          value: NDViYjdmNjBmMTE5NWI4MGQyNTZmMDhh
        - name: RABBITMQ_HOST
          value: rabbit
        - name: SURE_TOSCA_BASE_PATH
          value: http://sure-tosca:8081/tosca-sure/1.0.0
        - name: CREDENTIAL_SECRET
          value: 5Y-ABHuVBjls_Iui4faIU1Yoc2FRf5cjpQU5x5FJ1fI=
        - name: DELETE_TEMPLATES_AFTER_EXECUTION
          value: "False"
        image: qcdis/sdia-deployer:1.0.6
        name: deployer
        imagePullPolicy: Always
        resources: {}
      restartPolicy: Always
status: {}



