apiVersion: v1
kind: Service
metadata:
  namespace: sdia
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: manager
  name: manager
spec:
  type: NodePort  
  ports:
  - port: 8080
    nodePort: 30000
    protocol: TCP
    name: http
  selector:
    io.kompose.service: manager
status:
  loadBalancer: {}
