apiVersion: v1
kind: Service
metadata:
  namespace: sdia
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: orchestrator
  name: orchestrator
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 32092
    protocol: TCP
    name: http
#  ports:
#  - name: "8080"
#    port: 8080
#    targetPort: 8080
  selector:
    io.kompose.service: orchestrator
status:
  loadBalancer: {}
