apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lw
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: orchestrator
  name: orchestrator
spec:
  selector:
    matchLabels:
      io.kompose.service: orchestrator
  replicas: 1
  strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 50%
            maxUnavailable: 50%
  minReadySeconds: 10
  revisionHistoryLimit: 3
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: orchestrator
    spec:
      containers:
      - env:
        - name: MONGO_HOST
          value: mongo
        - name: RABBITMQ_HOST
          value: rabbit
        - name: SURE_TOSCA_BASE_PATH
          value: http://sure-tosca:8081/tosca-sure/1.0.0
        - name: CREDENTIAL_SECRET
          value: 5Y-ABHuVBjls_Iui4faIU1Yoc2FRf5cjpQU5x5FJ1fI=
        image: qcdis/sdia-orchestrator:1.0.6
        name: orchestrator
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
