apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lw
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: awx-task
  name: awx-task
spec:
  selector:
    matchLabels:
      io.kompose.service: awx-task
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: awx-task
    spec:
      containers:
      - args:
        - /usr/bin/launch_awx_task.sh
        env:
        - name: SUPERVISOR_WEB_CONFIG_PATH
          value: /etc/supervisord.conf
        image: ansible/awx:15.0.1
        name: awx-task
        resources: {}
        volumeMounts:
        - mountPath: /etc/tower/
          name: awx-config-volume
      hostname: awx-task
      restartPolicy: Always
      volumes:
      - name: awx-config-volume
        configMap:
          name: awx-config
          items:
            - key: SECRET_KEY
              path: SECRET_KEY
            - key: credentials.py
              path: conf.d/credentials.py
            - key: environment.sh
              path: conf.d/environment.sh
            - key: settings.py
              path: settings.py
status: {}
